In [1]:
#Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [34]:
import numpy as np

In [65]:
l=[1,2,3,4,5,6,7]
ar=np.array(object=l)

In [66]:
l

[1, 2, 3, 4, 5, 6, 7]

In [67]:
ar

array([1, 2, 3, 4, 5, 6, 7])

In [68]:
ar.dtype

dtype('int64')

In [73]:
ar1=np.array(l)

In [74]:
ar1

array([1, 2, 3, 4, 5, 6, 7])

In [75]:
ar1.dtype

dtype('int64')

In [76]:
#Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [77]:
import numpy as np

In [78]:
l=[1,2,3,4,5,6]

In [79]:
ar2=np.array(l)

In [80]:
ar2

array([1, 2, 3, 4, 5, 6])

In [81]:
ar3=np.array(l)

In [82]:
ar3

array([1, 2, 3, 4, 5, 6])

In [83]:
for i in ar3:
    print(i.dtype)

int64
int64
int64
int64
int64
int64


In [84]:
#Q3. Considering the following changes in the variable, array_list: array_list = np.array(object = list_, dtype = int)
#Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present 
#in both the variables, list_ and arra_list.



In [106]:
list_arr=([1,2,3],[4,5,6])

In [107]:
ar1=np.array(list_arr)

In [108]:
ar1

array([[1, 2, 3],
       [4, 5, 6]])

In [109]:
ar1.dtype

dtype('int64')

In [110]:
for i in ar1:
    print(i.dtype)

int64
int64


In [120]:
#Q4. Write a code to find the following characteristics of variable, num_array: (i)	 shape (ii) size

In [121]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

In [122]:
num_array = np.array(object = num_list)

In [123]:
num_list

[[1, 2, 3], [4, 5, 6]]

In [124]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [125]:
np.shape(num_list)

(2, 3)

In [126]:
np.size(num_list)

6

In [127]:
#Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

#[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [135]:
cr=np.zeros((3,3))

In [136]:
cr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [137]:
np.shape(cr)

(3, 3)

In [138]:
np.size(cr)

9

In [139]:
#Q6. Create an identity matrix of shape (5,5) using numpy functions?
#[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [144]:
ar34=np.eye(5,5)

In [145]:
ar34

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])